'use client';

import ScrollReveal from '@/components/ScrollReveal';
import FAQItem from '@/components/FAQItem';
import MagneticButton from '@/components/MagneticButton';

const faqs = [
  {
    q: 'What is CeloSaver?',
    a: 'CeloSaver is a save-to-earn application built on the Celo blockchain. It lets you deposit stablecoins (cUSD/cEUR) into a yield-generating vault, earn APY on your deposits, and unlock higher returns through streak-based multipliers.',
  },
  {
    q: 'How do I get started?',
    a: 'Connect your wallet (MiniPay, MetaMask, or any Celo-compatible wallet), deposit stablecoins into the vault, and your savings start earning yield automatically. That is it.',
  },
  {
    q: 'What wallets are supported?',
    a: 'Any wallet on the Celo network. This includes MiniPay (built into the Celo mobile wallet), MetaMask configured for Celo, and any WalletConnect-compatible wallet via Reown AppKit.',
  },
  {
    q: 'Are there any fees?',
    a: 'CeloSaver does not charge deposit or withdrawal fees. You only pay the standard Celo network transaction fee (typically less than $0.001 per transaction). Yield strategies may have internal protocol fees which are disclosed in the vault contract.',
  },
  {
    q: 'How is the APY calculated?',
    a: 'The APY reflects the annualized yield generated by the vault\'s DeFi strategies. It is variable and updated periodically. Your effective returns also depend on your streak multiplier — longer streaks amplify your yield.',
  },
  {
    q: 'Can I lose my deposited funds?',
    a: 'Like all DeFi applications, there are risks involved. These include smart contract risk, stablecoin de-pegging, and market volatility affecting yield strategies. We recommend only depositing what you can afford to lose. See the Safety & Risk page for full details.',
  },
  {
    q: 'How do streaks work?',
    a: 'Your streak increases by one day each time you make a deposit. If you go more than 3 days without depositing, your streak resets to zero. Longer streaks unlock multipliers: 1.2x (3 days), 1.5x (7 days), 2x (14 days), and 3x (30 days).',
  },
  {
    q: 'How do I withdraw my funds?',
    a: 'Navigate to the Vault page and use the withdraw function. Enter the amount you wish to withdraw and confirm the transaction. Funds are sent directly to your wallet. There are no lock-up periods.',
  },
  {
    q: 'Is there a minimum deposit?',
    a: 'There is no minimum deposit requirement. You can deposit any amount greater than zero. However, very small deposits may be uneconomical due to network transaction fees.',
  },
  {
    q: 'Is CeloSaver open source?',
    a: 'Yes. The smart contracts and frontend code are open source and available on GitHub. Contract addresses are visible on the Vault page and can be verified on Celo Explorer.',
  },
];

export default function FAQ() {
  return (
    <div className="min-h-dvh bg-[#050505]">
      <div className="fixed inset-0 pointer-events-none overflow-hidden">
        <div className="absolute bottom-[10%] right-[-10%] w-[50%] h-[50%] bg-[#0988F0]/5 rounded-full blur-[100px]" />
      </div>

      <div className="relative z-10 max-w-3xl mx-auto px-6 pt-32 pb-24">
        <ScrollReveal>
          <section className="text-center max-w-2xl mx-auto mb-16">
            <span className="inline-flex px-3 py-1 rounded-full bg-white/5 border border-white/10 text-[10px] uppercase tracking-[0.2em] font-medium text-white/50 mb-4">
              Help
            </span>
            <h1 className="font-sans text-4xl md:text-5xl text-white tracking-tight leading-[1.05]">
              Frequently asked questions
            </h1>
            <p className="font-sans text-[15px] text-white/40 mt-4 max-w-lg mx-auto">
              Everything you need to know about using CeloSaver.
            </p>
          </section>
        </ScrollReveal>

        <ScrollReveal>
          <div className="rounded-2xl bg-white/[0.02] border border-white/5 p-6">
            {faqs.map((faq, i) => (
              <FAQItem key={i} question={faq.q} answer={faq.a} />
            ))}
          </div>
        </ScrollReveal>

        <ScrollReveal delay={100}>
          <section className="text-center py-24">
            <h2 className="font-sans text-2xl text-white tracking-tight mb-2">Still have questions?</h2>
            <p className="font-sans text-[14px] text-white/40 mb-8">We are here to help.</p>
            <MagneticButton href="/dashboard" arrow>Open app</MagneticButton>
          </section>
        </ScrollReveal>
      </div>
    </div>
  );
}
